# Nixpacks configuration for Railway
# Installs system dependencies required by Playwright/Chromium

[phases.setup]
aptPkgs = [
    # Core system libraries
    "libnss3",
    "libnspr4",
    "libatk1.0-0",
    "libatk-bridge2.0-0",
    "libcups2",
    "libdrm2",
    "libdbus-1-3",
    "libxkbcommon0",
    "libxcomposite1",
    "libxdamage1",
    "libxfixes3",
    "libxrandr2",
    "libgbm1",
    "libpango-1.0-0",
    "libcairo2",
    "libasound2",
    "libatspi2.0-0",
    "libxshmfence1",
    # X11 libraries
    "libx11-6",
    "libxcb1",
    "libxext6",
    # Fonts
    "fonts-liberation",
    "fonts-noto-color-emoji",
    # Additional utilities
    "wget",
    "ca-certificates"
]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "python -m playwright install chromium",
    "python -m playwright install-deps chromium"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 600 app:app"
